# k8s/system/postgres-dds.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-dds
  labels:
    app: postgres-dds
spec:
  serviceName: "postgres-dds"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dds
  template:
    metadata:
      labels:
        app: postgres-dds
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-dds-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-dds-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-dds-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi